version: '3.9'
services:
  node:
    build: 
      context: remix
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./:/app"
      - "/app/node_modules/"