version: '3.9'
services:
  remixnode:
    build: 
      context: ./remix
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "/app/node_modules"
      - "./remix:/app"