version: '3.9'
services:
  remixnode:
    build: 
      context: ./remix
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - '/app/node_modules'
      - './remix:/app'
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=NodePrismaApp2022!
    ports:
      - '1437:1433'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - '8087:80'